# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aet-platform
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aet-platform
  template:
    metadata:
      labels:
        app: aet-platform
    spec:
      containers:
      - name: aet-quantum
        image: aet/quantum-core:latest
        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
          limits:
            memory: "32Gi"
            cpu: "8"
        env:
          - name: NODE_ENV
            value: "production"
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: aet-secrets
                key: redis-url
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: aet-secrets
                key: database-url

      - name: aet-ai
        image: aet/ai-core:latest
        resources:
          requests:
            memory: "32Gi"
            cpu: "8"
          limits:
            memory: "64Gi"
            cpu: "16"

      - name: aet-evolution
        image: aet/evolution-core:latest
        resources:
          requests:
            memory: "16Gi"
            cpu: "4"

---
# kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aet-platform
  namespace: production
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 3000
  selector:
    app: aet-platform

---
# kubernetes/autoscaling.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aet-platform
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aet-platform
  minReplicas: 3
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
# kubernetes/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aet-platform
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.aparicioedge.tech
    secretName: aet-tls
  rules:
  - host: api.aparicioedge.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aet-platform
            port:
              number: 443
